apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mi-app
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: nuevonginx.bce.fin.ec
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mi-app
                port:
                  number: 80
